package com.gamelibrary.gamelibrary.entity;

import jakarta.persistence.*;
import lombok.Data;

@Data //Autogenerated setters and getters, toString
@Entity //say to Spring boot: this class is table in DB
@Table(name = "games") // Name for table
public class Game {
  
  @Id //like "PRIMARY KEY"
  @GeneratedValue(strategy = GenerationType.UUID) //autogenerated id
  private String id;

  private String title;
  private String genre;
  private String platform;
  private Integer releaseYear;
  private String coverUrl;
}
