package com.gamelibrary.gamelibrary.entity;

import jakarta.persistence.*;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Max;

@Data //Autogenerated setters and getters, toString
@Entity //say to Spring boot: this class is table in DB
@Table(name = "games") // Name for table
public class Game {
  
  @Id //like "PRIMARY KEY"
  @GeneratedValue(strategy = GenerationType.UUID) //autogenerated id
  private String id;

  @NotBlank(message = "Title cannot be empty")
  private String title;

  @NotBlank(message = "Genre cannot be empty")
  private String genre;
  
  @NotBlank(message = "Platform cannot be empty")
  private String platform;

  @Min(value = 1950, message = "Year must be after 1950")
  @Max(value = 2030, message = "Year must be before 2030")
  private Integer releaseYear;

  private String coverUrl;
}
