spring.application.name=gamelibrary

spring.datasource.url=jdbc:postgresql://localhost:5432/gamelibrary
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

server.error.include-message=always
server.error.include-stacktrace=always
